viikko1: viikkoraportti1.tex
	pdflatex viikkoraportti1.tex
	mv viikkoraportti1.pdf ../../viikkoraportti1.pdf

viikko2: viikkoraportti2.tex
	pdflatex viikkoraportti2.tex
	mv viikkoraportti2.pdf ../../viikkoraportti2.pdf
