viikko1: viikkoraportti1.tex
	pdflatex viikkoraportti1.tex
	mv viikkoraportti1.pdf ../../viikkoraportti1.pdf

viikko2: viikkoraportti2.tex
	pdflatex viikkoraportti2.tex
	mv viikkoraportti2.pdf ../../viikkoraportti2.pdf

viikko3: viikkoraportti3.tex
	pdflatex viikkoraportti3.tex
	mv viikkoraportti3.pdf ../../viikkoraportti3.pdf

viikko4: viikkoraportti4.tex
	pdflatex viikkoraportti4.tex
	mv viikkoraportti4.pdf ../../viikkoraportti4.pdf

viikko5: viikkoraportti5.tex
	pdflatex viikkoraportti5.tex
	mv viikkoraportti5.pdf ../../viikkoraportti5.pdf

viikko6: viikkoraportti6.tex
	pdflatex viikkoraportti6.tex
	mv viikkoraportti6.pdf ../../viikkoraportti6.pdf
